### ISSUE TITLE
Unable to launch v1.11.1 with JDK "11.0.7"

### ISSUE THREAD

**Issue by Shroototem** [Querz/mcaselector#120]
Not opening application..

**To Reproduce**
Tried to open by double clicking but program did not launch.
Then used CMD with this command "java -jar mcaselector-1.11.1.jar" but it gave an error.

Exception in thread "main" java.lang.NoClassDefFoundError: javafx/beans/property/StringProperty
        at net.querz.mcaselector.Main.main(Main.java:29)
Caused by: java.lang.ClassNotFoundException: javafx.beans.property.StringProperty
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

Windows 10 - Pro
JDK "11.0.7"
mcaselector-1.11.1

**Comment by Shroototem** [comment]
I managed to fix the issue by modifying the registry. Sorry for the post.
