### ISSUE TITLE
Import Chunks not working

### ISSUE THREAD

**Issue by zachman42** [Querz/mcaselector#131]
Whenever I attempt to import chunks from one world to another, nothing happens and the debug log prints this:

java.lang.Exception: failed to process chunk import for r.0.-1.mca
	at net.querz.mcaselector.debug.Debug.dumpException(Debug.java:79)
	at net.querz.mcaselector.io.ChunkImporter$MCAChunkImporterProcessJob.execute(ChunkImporter.java:286)
	at net.querz.mcaselector.io.ProcessDataJob.run(ProcessDataJob.java:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

java.lang.NullPointerException
	at net.querz.mcaselector.io.ChunkImporter$MCAChunkImporterProcessJob.execute(ChunkImporter.java:280)
	at net.querz.mcaselector.io.ProcessDataJob.run(ProcessDataJob.java:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I've tried applying my brain, but I think I need a new one.

**Comment by zachman42** [comment]
I should note I am using the recommended version of Java, and ram doesn't seem to be an issue.

**Comment by Querz** [comment]
Fixed this bug in [release 1.12.2](https://github.com/Querz/mcaselector/releases/tag/1.12.2).
