### ISSUE TITLE
still having issues with importing chunks

### ISSUE THREAD

**Issue by zachman42** [Querz/mcaselector#133]
This is effecting the copy and paste action too this time:

merging chunk from region <-1, -1> into <-1, -1>
java.lang.Exception: validation error
	at net.querz.mcaselector.debug.Debug.dumpException(Debug.java:79)
	at net.querz.mcaselector.validation.ValidationHelper.catchClassCastException(ValidationHelper.java:23)
	at net.querz.mcaselector.io.MCAChunkData.applyOffsetToStructures(MCAChunkData.java:282)
	at net.querz.mcaselector.io.MCAChunkData.relocate(MCAChunkData.java:270)
	at net.querz.mcaselector.io.MCAFile.mergeChunksInto(MCAFile.java:356)
	at net.querz.mcaselector.io.ChunkImporter$MCAChunkImporterProcessJob.execute(ChunkImporter.java:280)
	at net.querz.mcaselector.io.ProcessDataJob.run(ProcessDataJob.java:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

java.lang.ClassCastException: Cannot cast net.querz.nbt.tag.ByteArrayTag to net.querz.nbt.tag.CompoundTag
	at java.lang.Class.cast(Unknown Source)
	at net.querz.nbt.tag.CompoundTag.get(CompoundTag.java:74)
	at net.querz.nbt.tag.CompoundTag.getCompoundTag(CompoundTag.java:128)
	at net.querz.mcaselector.io.MCAChunkData.lambda$applyOffsetToStructures$10(MCAChunkData.java:282)
	at net.querz.mcaselector.validation.ValidationHelper.catchClassCastException(ValidationHelper.java:21)
	at net.querz.mcaselector.io.MCAChunkData.applyOffsetToStructures(MCAChunkData.java:282)
	at net.querz.mcaselector.io.MCAChunkData.relocate(MCAChunkData.java:270)
	at net.querz.mcaselector.io.MCAFile.mergeChunksInto(MCAFile.java:356)
	at net.querz.mcaselector.io.ChunkImporter$MCAChunkImporterProcessJob.execute(ChunkImporter.java:280)
	at net.querz.mcaselector.io.ProcessDataJob.run(ProcessDataJob.java:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

java.lang.NullPointerException
	at net.querz.mcaselector.debug.Debug$ExceptionInfo.equals(Debug.java:256)
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.containsKey(Unknown Source)
	at net.querz.mcaselector.debug.Debug.error(Debug.java:59)
	at net.querz.mcaselector.debug.Debug.dumpException(Debug.java:79)
	at net.querz.mcaselector.validation.ValidationHelper.catchClassCastException(ValidationHelper.java:23)
	at net.querz.mcaselector.io.MCAChunkData.applyOffsetToStructures(MCAChunkData.java:299)
	at net.querz.mcaselector.io.MCAChunkData.relocate(MCAChunkData.java:270)
	at net.querz.mcaselector.io.MCAFile.mergeChunksInto(MCAFile.java:356)
	at net.querz.mcaselector.io.ChunkImporter$MCAChunkImporterProcessJob.execute(ChunkImporter.java:280)
	at net.querz.mcaselector.io.ProcessDataJob.run(ProcessDataJob.java:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

It's bizarre because it was working fine, then randomly stopped working.

**Comment by Querz** [comment]
For some reason your world has a chunk where the `Reference` data for structures in a ByteArrayTag instead of CompoundTag. This should not affect the chunk import, it's just dumping this Exception to the console because it did not expect it to be this way.

What Minecraft version was used to generate the chunks that you're trying to import? Did you use the "Optimize World" feature in Minecraft to upgrade those chunks to a newer version? Could you send me the  source `r.-1.-1.mca` file?

**Comment by zachman42** [comment]
Ok so I checked and the versions were different. I optimized both worlds and tried again but got the same result. I tried earlier versions of MCA selector and it still didn't work so I'm starting to think it is on my end. I attached both the mca file and the debug log.

[stuff.zip](https://github.com/Querz/mcaselector/files/4948836/stuff.zip)
