### ISSUE TITLE
Missing development doc

### ISSUE THREAD

**Issue by mkyral** [Querz/mcaselector#25]
Hi,
I want translate this useful program to Czech but I don't know, how to properly build this for testing.

I was able to build jar, but it fails on missing net/querz/nbt/Tag class. I can build NBT:4, but have no idea, how to merge them together.

**Comment by Querz** [comment]
By running the gradle task "shadowJar" it will create a jar that contains all dependencies.
I will add this information to the readme.

**Comment by mkyral** [comment]
Thanks. I've tested, but it still does not bundle NTB lib. Do I need to clone it to specific space?

```
$ bash gradlew build minifyCss shadowJar
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Djava.net.preferIPv4Stack=true
:compileJava
:processResources
:classes
:jar
:assemble
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:build
:minifyCss
:shadowJar

BUILD SUCCESSFUL in 1s
5 actionable tasks: 5 executed
[07:26:46 marian@Latitude-5591-6 mcaselector.clone (master)]$ java -jar build/libs/mcaselector-1.7.4.jar 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Djava.net.preferIPv4Stack=true
Gtk-Message: 07:27:20.268: Failed to load module "canberra-gtk-module"
Exception in thread "pool-3-thread-1" Exception in thread "pool-3-thread-3" Exception in thread "pool-3-thread-2" java.lang.NoClassDefFoundError: net/querz/nbt/Tag
        at net.querz.mcaselector.io.MCAChunkData.loadData(MCAChunkData.java:59)
        at net.querz.mcaselector.io.MCAFile.createImage(MCAFile.java:363)
        at net.querz.mcaselector.tiles.Tile.generateImage(Tile.java:291)
        at net.querz.mcaselector.io.RegionImageGenerator$MCAImageProcessJob.execute(RegionImageGenerator.java:86)
        at net.querz.mcaselector.io.ProcessDataJob.run(ProcessDataJob.java:21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Querz** [comment]
Make sure to run the correct jar file, because it creates both: a jar without and a jar with dependencies.
The jar you want to run in this case is `build/libs/mcaselector-1.7.4-all.jar`

**Comment by mkyral** [comment]
Ou, I see.
It works now. Thanks.
