### ISSUE TITLE
Installed but not working.. 

### ISSUE THREAD

**Issue by quewn** [Querz/mcaselector#325]
D:\Program Files (x86)\MCA Selector>"MCA Selector.exe"

D:\Program Files (x86)\MCA Selector>[info] Module Name: D:\Program Files (x86)\MCA Selector\MCA Selector.exe
[info] Module INI: D:\Program Files (x86)\MCA Selector\MCA Selector.ini
[info] Module Dir: D:\Program Files (x86)\MCA Selector\
[info] INI Dir: D:\Program Files (x86)\MCA Selector\
[info] Configured vm.location: zulu17.30.15-ca-fx-jre17.0.1-win_x64\bin\server\jvm.dll
[info] Found VM: D:\Program Files (x86)\MCA Selector\zulu17.30.15-ca-fx-jre17.0.1-win_x64\bin\server\jvm.dll
[info] Expanding Classpath: mcaselector.jar
[info] Expanding Classpath: lib\*.jar
[info] Expanding Classpath: D:\Program Files (x86)\MCA Selector\lib/fastutil-8.5.6.jar
[info] Expanding Classpath: D:\Program Files (x86)\MCA Selector\lib/json-20201115.jar
[info] Expanding Classpath: D:\Program Files (x86)\MCA Selector\lib/NBT-4192a95c9d.jar
[info] Expanding Classpath: D:\Program Files (x86)\MCA Selector\lib/pngj-2.1.0.jar
[info] Expanding Classpath: D:\Program Files (x86)\MCA Selector\lib/sqlite-jdbc-3.34.0.jar
[info] Generated Classpath: D:\Program Files (x86)\MCA Selector\mcaselector.jar;D:\Program Files (x86)\MCA Selector\lib\fastutil-8.5.6.jar;D:\Program Files (x86)\MCA Selector\lib\json-20201115.jar;D:\Program Files (x86)\MCA Selector\lib\NBT-4192a95c9d.jar;D:\Program Files (x86)\MCA Selector\lib\pngj-2.1.0.jar;D:\Program Files (x86)\MCA Selector\lib\sqlite-jdbc-3.34.0.jar
[info] VM Args:
[info] vmarg.0=-Djava.class.path=D:\Program Files (x86)\MCA Selector\mcaselector.jar;D:\Program Files (x86)\MCA Selector\lib\fastutil-8.5.6.jar;D:\Program Files (x86)\MCA Selector\lib\json-20201115.jar;D:\Program Files (x86)\MCA Selector\lib\NBT-4192a95c9d.jar;D:\Program Fi
[info] vmarg.1=-Xmx4096m
[info] Registering natives for Native class
[warn] Could not find Native class
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
        at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
        at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "com.sun.glass.ui.Screen.getNativeScreen()" because "<parameter1>" is null
        at javafx.graphics/com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

(ctrl + C)

D:\Program Files (x86)\MCA Selector>Exception in thread "Glass/Prism Shutdown Hook" java.lang.NullPointerException: Cannot invoke "com.sun.glass.ui.Timer.stop()" because "this.pulseTimer" is null
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.dispose(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit$1.run(Unknown Source)
[info] Application exited (130).

**Comment by quewn** [comment]
windows10(21H1) 19043.1466
latest msi 1.17.2 with all recommended settings

**Comment by quewn** [comment]
p.s. works with >(provided jre)java.exe -jar "D:\Program Files (x86)\MCA Selector\mcaselector-1.17.2.jar"
