### ISSUE TITLE
Default process threads count causes out of memory errors with high core CPU

### ISSUE THREAD

**Issue by DefectiveNu** [Querz/mcaselector#328]
when using a high core count cpu (32 in my case) the default values for process-threads (30) causes out of memory errors which stalls processing at some point

**To Reproduce**
1. run commandline: MCA Selector.exe --mode delete --region world\region --query "InhabitedTime = 0"
2. log should show some threads reporting "java.lang.OutOfMemoryError: Java heap space"
3. progress will stall before completion (assuming its waiting for the crashed threads)

**Expected behavior**
process eventually finishes

**Screenshots and other files**
CLI output seems a bit garbled but here's the relevant segment:
```88.27%  r.2.-13.mca
Exception in thread "processPool-thread-13" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.io.BufferedInputStream.<init>(Unknown Source)
        at java.base/java.io.BufferedInputStream.<init>(Unknown Source)
        at net.querz.mcaselector.io.mca.Chunk.load(Chunk.java:47)
        at net.querz.mcaselector.io.mca.MCAFile.load(MCAFile.java:252)
        at net.querz.mcaselector.io.mca.Region.loadRegion(Region.java:111)
        at net.querz.mcaselector.io.mca.Region.loadRegion(Region.java:32)
        at net.querz.mcaselector.io.job.ChunkFilterDeleter$MCADeleteFilterProcessJob.execute(ChunkFilterDeleter.java:78)
        at net.querz.mcaselector.io.job.ProcessDataJob.run(ProcessDataJob.java:73)
        at net.querz.mcaselector.io.JobHandler$WrapperJob.run(JobHandler.java:237)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "processPool-thread-5" [03:01:05.112] failed to load any data from java.lang.OutOfMemoryError: Java heap space
r.-15.9.mca
88.56%  r.-15.9.mca
[03:01:05.427] failed to load any data from Exception in thread "processPool-thread-32" r.-15.10.mcajava.lang.OutOfMemoryError: Java heap space

88.86%  r.-15.10.mca
```

note: its not always at the same file

**Comment by NotGeri** [comment]
Can confirm that it's happening on the latest release, though I'm not too sure what might be considered as a higher CPU core count. In this case, we specified 8 with the `--process-threads` flag.

This is what htop shows: 
![img](https://i.geri.dev/38GlcY.png)

It seems to be spamming the generic OOM exception every now and then:

```
[1565.893s][warning][gc,alloc] processPool-thread-7: Retried waiting for GCLocker too often allocating 258 words
Exception in thread "processPool-thread-7" java.lang.OutOfMemoryError: Java heap space
	at net.querz.nbt.io.NBTInputStream.readLongArray(NBTInputStream.java:119)
	at net.querz.nbt.io.NBTInputStream.lambda$static$10(NBTInputStream.java:43)
	at net.querz.nbt.io.NBTInputStream$$Lambda$58/0x0000000800c1f9f8.accept(Unknown Source)
	at net.querz.nbt.io.NBTInputStream.readTag(NBTInputStream.java:70)
	at net.querz.nbt.io.NBTInputStream.readCompound(NBTInputStream.java:144)
	at net.querz.nbt.io.NBTInputStream$$Lambda$56/0x0000000800c1f5b8.accept(Unknown Source)
	at net.querz.nbt.io.NBTInputStream.readTag(NBTInputStream.java:70)
	at net.querz.nbt.io.NBTInputStream.readCompound(NBTInputStream.java:144)
	at net.querz.nbt.io.NBTInputStream$$Lambda$56/0x0000000800c1f5b8.accept(Unknown Source)
	at net.querz.nbt.io.NBTInputStream.readTag(NBTInputStream.java:70)
	at net.querz.nbt.io.NBTInputStream.readListTag(NBTInputStream.java:135)
	at net.querz.nbt.io.NBTInputStream$$Lambda$55/0x0000000800c1f398.accept(Unknown Source)
	at net.querz.nbt.io.NBTInputStream.readTag(NBTInputStream.java:70)
	at net.querz.nbt.io.NBTInputStream.readCompound(NBTInputStream.java:144)
	at net.querz.nbt.io.NBTInputStream$$Lambda$56/0x0000000800c1f5b8.accept(Unknown Source)
	at net.querz.nbt.io.NBTInputStream.readTag(NBTInputStream.java:70)
	at net.querz.nbt.io.NBTInputStream.readTag(NBTInputStream.java:57)
	at net.querz.nbt.io.NBTDeserializer.fromStream(NBTDeserializer.java:41)
	at net.querz.mcaselector.io.mca.Chunk.load(Chunk.java:54)
	at net.querz.mcaselector.io.mca.MCAFile.load(MCAFile.java:252)
	at net.querz.mcaselector.io.mca.Region.loadRegion(Region.java:111)
	at net.querz.mcaselector.io.mca.Region.loadRegion(Region.java:32)
	at net.querz.mcaselector.io.job.ChunkFilterDeleter$MCADeleteFilterProcessJob.execute(ChunkFilterDeleter.java:78)
	at net.querz.mcaselector.io.job.ProcessDataJob.run(ProcessDataJob.java:73)
	at net.querz.mcaselector.io.JobHandler$WrapperJob.run(JobHandler.java:237)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

The system has plenty of memory left.

I will try to run some test to see what might be happening here.

**Comment by Querz** [comment]
Added a hard limit of 4 threads in 1.17.3. This can still be increased manually if needed.
