### ISSUE TITLE
MCA not working on mac

### ISSUE THREAD

**Issue by Chillarity** [Querz/mcaselector#348]
**Describe the bug**
MCA version 1.17.3 is not opening on mac

**To Reproduce**
1. download the jar file
2. open it
3. gives the message: "Java application launch failed. Check Console for possible error messages related to "/Users/name/Downloads/mcaselector-1.17.3"."

**Expected behavior**
the program would run

**Environment (please complete the following information):**
- OS: MacOS
- Java version: 17
- Version of MCA Selector 1.17.3

**Comment by thefella** [comment]
Same here

**Comment by fjcanas** [comment]
When run from a command line using java -jar the message is:
Error: LinkageError occurred while loading main class net.querz.mcaselector.Main
	java.lang.UnsupportedClassVersionError: net/querz/mcaselector/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 57.0

I am running Java Version 8 Update 333 (build 1.8.0_333-b02)

**Comment by tompayne36** [comment]
Same problem

**Comment by SoftwareMaven** [comment]
That error indicates the class files have been compiled with a newer version of Java than the version you are running it with. You probably need to upgrade your java runtime.

**Comment by tompayne36** [comment]
I got it to work by using the version of Java listed on the install page (zulu17.30.51-ca-fx-jre17.0.1-macosx_x64.zip). That appears to report:

openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu17.30+51-CA (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu17.30+51-CA (build 17.0.1+12-LTS, mixed mode, sharing)

When I download the latest version of Java from java.com (today), it reports:

java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)

The versioning of Java is very confusing.

**Comment by tmcelrath** [comment]
Same problem, I'm using the latest Java runtime (same as above). I redownloaded and reopened MCA Selector after hitting this bug and then having to upgrade my Java runtime. Same error.

**Comment by BesaBlock** [comment]
I too am having the same issue. Running macOS Monterey Version 12.4 with Java Version 8 Update 333 and get the error:
'Java application launch failed. Check Console for possible error messages related to "/Users/name/Downloads/mcaselector-1.17.3'
when trying to open mcaselector-1.17.3.jar file.

**Comment by ABUCKY0** [comment]
What version of java appears when you run `java --version`

**Comment by BesaBlock** [comment]
user@User-iMac ~ % java -version
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)

**Comment by ABUCKY0** [comment]
Go to the command line, use cd Users/name/Downloads/ and then use java -jar mcaselector-1.17.3.jar and tell me what the console prints

> user@User-iMac ~ % java -version java version "1.8.0_333" Java(TM) SE Runtime Environment (build 1.8.0_333-b02) Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)

**Comment by BesaBlock** [comment]
user@User-iMac Downloads % java -jar mcaselector-1.17.3.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/querz/mcaselector/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

I see also that mcaselector-2.0.jar is now available. I've downloaded and tried the same command for that too.

user@User-iMac Downloads % java -jar mcaselector-2.0.jar   
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/querz/mcaselector/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

**Comment by ABUCKY0** [comment]
Update Java. mcaselector was compiled with a newer version of java.

ie `Exception in thread "main" java.lang.UnsupportedClassVersionError: net/querz/mcaselector/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

is saying `Uh Oh, This program was made with a newer version of Java, With class version 61. I only support class versions up to Class Version 52`

**Comment by BesaBlock** [comment]
Okay, so I think what your saying is that it won't work because you don't support it?
If this is the case, will you support it in the future or will I not be able to use mcaselector again?

**Comment by ABUCKY0** [comment]
Java has different versions, similarly to how minecraft updates. To get the new blocks (or in this case, the program access), you need to update java. Mac is supported, you just need to update java.
Look up a youtube video on how to do so

**Comment by tompayne36** [comment]
It is not about updating Java. It is about using the right/supported version. Use the "zulu" version from the install page.

**Comment by BesaBlock** [comment]
> Java has different versions, similarly to how minecraft updates. To get the new blocks (or in this case, the program access), you need to update java. Mac is supported, you just need to update java.
> Look up a youtube video on how to do so

I have already done this.

**Comment by tompayne36** [comment]
From the macOS section of this page: https://github.com/Querz/mcaselector/wiki/Installation

https://cdn.azul.com/zulu/bin/zulu17.30.51-ca-fx-jre17.0.1-macosx_x64.zip

**Comment by BesaBlock** [comment]
> https://cdn.azul.com/zulu/bin/zulu17.30.51-ca-fx-jre17.0.1-macosx_x64.zip

Thankyou tompayne36 that work!

**Comment by BesaBlock** [comment]
*worked
