### ISSUE TITLE
javafx error on headless import

### ISSUE THREAD

**Issue by uriesk** [Querz/mcaselector#35]
I get a NoClassDefFoundError when restoring with the command:
java -jar mcaselector-1.8.2.jar --headless --mode import --world "${WORLD}" --input "${FOLDER}" --overwrite
The release notes on 1.8.2 say that javafx is not needed for headless mode, so i thought i will report it.
Interestingly this error is thrown even thought that openjfx is installed, but i guess thats another issue based on my setup or something (Ubuntu 18.04.2 LTS).

`read threads:    1
process threads: 8
write threads:   4
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/beans/property/StringProperty
        at net.querz.mcaselector.io.ChunkImporter.importChunks(ChunkImporter.java:33)
        at net.querz.mcaselector.headless.ParamExecutor.runModeImport(ParamExecutor.java:210)
        at net.querz.mcaselector.headless.ParamExecutor.lambda$parseAndRun$4(ParamExecutor.java:83)
        at net.querz.mcaselector.headless.ParamInterpreter.execute(ParamInterpreter.java:133)
        at net.querz.mcaselector.headless.ParamExecutor.parseAndRun(ParamExecutor.java:88)
        at net.querz.mcaselector.Main.main(Main.java:17)
Caused by: java.lang.ClassNotFoundException: javafx.beans.property.StringProperty
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 6 more`

**Comment by uriesk** [comment]
Here the bug that caused my openjfx to not work:
https://bugs.launchpad.net/ubuntu/+source/openjfx/+bug/1799946
after doing that suggested workaround there, i could finally run it

But the bug that javajfx is required for headless import in the first place still stands

**Comment by Querz** [comment]
Fixed it in [release 1.8.3](https://github.com/Querz/mcaselector/releases/tag/1.8.3), alongside another bug that caused chunk import to freeze when importing with an offset that was not a multiple of 32.

Keep in mind that using `--mode cache` still requires JavaFX for rendering the images in headless mode.
