### ISSUE TITLE
Unable to Change Fields

### ISSUE THREAD

**Issue by Dracconis** [Querz/mcaselector#366]
**Bug Description**
Unable to "Change Fields" despite have 1 or more chunks selected like you could in previous versions.

**Expected behavior**
Expected this version to act like previous versions and allow the change of fields.

**Environment (please complete the following information):**
- OS: Win 10
- Java version: 17.0.1
- Version of MCA Selector 2.0.2

**Additional context**
- Minecraft 1.19
- Previously used MCA Selector 1.17.3

**Comment by UltraBlackLinux** [comment]
the nbt editor is crashing (I think taht's change fields, is it not?):
```
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider org.codehaus.groovy.jsr223.GroovyScriptEngineFactory not found
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "net.querz.mcaselector.changer.fields.CustomField.engine" is null
	at net.querz.mcaselector.changer.fields.CustomField.<init>(CustomField.java:28)
	at net.querz.mcaselector.changer.FieldType.newInstance(FieldType.java:53)
	at net.querz.mcaselector.ui.dialog.ChangeNBTDialog.<init>(ChangeNBTDialog.java:80)
	at net.querz.mcaselector.ui.DialogHelper.changeFields(DialogHelper.java:60)
	at net.querz.mcaselector.ui.component.OptionBar.lambda$new$30(OptionBar.java:179)
```
