### ISSUE TITLE
java.lang.NullPointerException Anvil113ChunkDataProcessor

### ISSUE THREAD

**Issue by andris155** [Querz/mcaselector#44]
```
java.lang.NullPointerException
        at net.querz.mcaselector.version.anvil113.Anvil113ChunkDataProcessor.drawChunk(Anvil113ChunkDataProcessor.java:14)
        at net.querz.mcaselector.tiles.TileImage.drawChunkImage(TileImage.java:141)
        at net.querz.mcaselector.tiles.TileImage.createMCAImage(TileImage.java:125)
        at net.querz.mcaselector.tiles.TileImage.generateImage(TileImage.java:96)
        at net.querz.mcaselector.io.RegionImageGenerator$MCAImageProcessJob.execute(RegionImageGenerator.java:106)
        at net.querz.mcaselector.io.ProcessDataJob.run(ProcessDataJob.java:21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Querz** [comment]
This error occurs when a chunk does not contain a "Level" or "Sections" tag. The error should only affect the rendering of a single chunk and not cancel the rendering of the entire region.

I wrote a fix for that and added more checks if other tags are missing or are of the wrong type. The console will only display an error message when the debug mode is enabled.
The changes are on master, if you want to test it yourself.
