### ISSUE TITLE
Crash when executed when executing "mcaselector-1.8.3.jar"

### ISSUE THREAD

**Issue by BinaryVigilante** [Querz/mcaselector#45]
Hello! When I run mcaselector-1.8.3.jar, I get this crash:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/beans/property/StringProperty
	at net.querz.mcaselector.Main.main(Main.java:25)
Caused by: java.lang.ClassNotFoundException: javafx.beans.property.StringProperty
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

```

I'm using Xubuntu 18.04, openjdk-8-jdk & openjdk-8-jre

**Comment by Querz** [comment]
You do not have JavaFX installed, please refer to #6 for this problem.

**Comment by Querz** [comment]
Duplicate of #6
