### ISSUE TITLE
Crash on run with Oracle Java SE 13

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [Querz/mcaselector#58]
I am assuming JRE 8+ requirement means that mcaselector should be compatible with [Oracle JDK 13](https://www.oracle.com/technetwork/java/javase/downloads/jdk13-downloads-5672538.html) too, but it is not:

```
> "C:\Program Files\Java\jdk-13.0.1\bin\java.exe" -jar mcaselector-1.9.1.jar

Exception in thread "main" java.lang.NoClassDefFoundError: javafx/beans/property/StringProperty
        at net.querz.mcaselector.Config.setLocale(Config.java:87)
        at net.querz.mcaselector.Config.loadFromIni(Config.java:129)
        at net.querz.mcaselector.Main.main(Main.java:24)
Caused by: java.lang.ClassNotFoundException: javafx.beans.property.StringProperty
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more
```

**Comment by Querz** [comment]
JavaFX does not automatically come with the JDK since Java 11 because of the modularisation.
The JavaFX modules must be added manually to the JDK.

**Comment by 0xfeeddeadbeef** [comment]
@Querz Thanks. I've solved the problem by installing [JavaFX 13](https://gluonhq.com/products/javafx/) SDK and then running mcaselector using this command line:

```
"C:\Program Files\Java\jdk-13.0.1\bin\java.exe" --module-path "C:\Program Files\Java\javafx-sdk-13.0.1\lib" --add-modules ALL-MODULE-PATH -jar mcaselector-1.9.1.jar
```
