### ISSUE TITLE
Error: Null

### ISSUE THREAD

**Issue by DefinePvP** [Querz/mcaselector#60]
I am looking to import a part of one world into another world, but I get this error:

```
Error: null
java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at net.querz.mcaselector.headless.ParamExecutor.parseFile(ParamExecutor.java:322)
        at net.querz.mcaselector.headless.ParamExecutor.runModeImport(ParamExecutor.java:205)
        at net.querz.mcaselector.headless.ParamExecutor.lambda$parseAndRun$4(ParamExecutor.java:84)
        at net.querz.mcaselector.headless.ParamInterpreter.execute(ParamInterpreter.java:133)
        at net.querz.mcaselector.headless.ParamExecutor.parseAndRun(ParamExecutor.java:89)
        at net.querz.mcaselector.Main.main(Main.java:17)

```
These are the commands I use.  The second one gives the error:

Hunter@dynmap:/mnt$ java -jar mcaselector-1.9.2.jar --headless --mode export --world /mnt/customterrain/customterrain/world/region/ --output /mnt/paper/paper/ct/  --query "xPos > -16 AND xPos < 16"

Hunter@dynmap:/mnt$ java -jar mcaselector-1.9.2.jar --headless --mode import --world /mnt/paper/paper/world/region/ --input /mnt/paper/paper/ct/ --debug

I am running Ubuntu 18.04 with OpenJDK 1.8.0 and with the JavaFX package installed.

edit: I didn't use my brain to read the documentation.  This might actually be working, but I was using block offsets instead of chunk offsets.  Give me a day to test it.

**Comment by Querz** [comment]
Your command is absolutely fine. There was actually a bug with importing chunks in headless mode throwing an error when not providing a selection file. This is fixed in [release 1.9.3](https://github.com/Querz/mcaselector/releases).
