### ISSUE TITLE
Unsupported locale en_GB crash on start

### ISSUE THREAD

**Issue by Neubulae** [Querz/mcaselector#82]
`Exception in thread "main" java.lang.IllegalArgumentException: unsupported locale en_GB
        at net.querz.mcaselector.text.Translation.load(Translation.java:222)
        at net.querz.mcaselector.Main.main(Main.java:29)`

**Comment by Querz** [comment]
What java version are you using?
How are you running the jar file (double click, command, ...)?
What OS are you using?

**Comment by Neubulae** [comment]
> What java version are you using?
> How are you running the jar file (double click, command, ...)?
> What OS are you using?

Java8u221, is that too old? I used command to open it

**Comment by Querz** [comment]
No, that java version is fine. The only way this error can happen is when the english language file is somehow missing. Did you make any changes to the jar file? Also make sure to use the [latest version](https://github.com/Querz/mcaselector/releases) of the MCA Selector.

**Comment by Neubulae** [comment]
> No, that java version is fine. The only way this error can happen is when the english language file is somehow missing. Did you make any changes to the jar file? Also make sure to use the [latest version](https://github.com/Querz/mcaselector/releases) of the MCA Selector.

I am using the latest version, lemme see if redownloading works

**Comment by Querz** [comment]
@Neubulae Did redownloading fix this issue?

**Comment by Neubulae** [comment]
> @Neubulae Did redownloading fix this issue?
Sorry for not getting enough time to reply but yes it did, thx for the support

**Comment by assombrance** [comment]
Hi, I seem to have the same problem : Fresh download and the following exception
```
        at net.querz.mcaselector.debug.Debug.dumpException(Debug.java:90)
        at net.querz.mcaselector.text.Translation.getResourceListing(Translation.java:277)
        at net.querz.mcaselector.text.Translation.<clinit>(Translation.java:150)
        at net.querz.mcaselector.Main.main(Main.java:36)
java.io.FileNotFoundException: D:\Documents\My games\minecraft\MC  \mcaselector-1.13.3.jar (The system cannot find the path specified)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:220)
        at java.util.zip.ZipFile.<init>(ZipFile.java:150)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at net.querz.mcaselector.text.Translation.getResourceListing(Translation.java:275)
        at net.querz.mcaselector.text.Translation.<clinit>(Translation.java:150)
        at net.querz.mcaselector.Main.main(Main.java:36)
Exception in thread "main" java.lang.IllegalArgumentException: unsupported locale en_GB
        at net.querz.mcaselector.text.Translation.load(Translation.java:230)
        at net.querz.mcaselector.Main.main(Main.java:36)
```
I tried downloading is again but no success.

**Comment by assombrance** [comment]
OK, self correction, I'm on Windows and I noticed that the path was wrong here : 
`> "D:\Documents\My games\minecraft\MC  \mcaselector-1.13.3.jar"`
There was a "+" sign in my path. I was a dummy when I created a folder with a "+" in its name !
I simply removed the "+" and it worked !
Thanks for the amazing software ! :D
